# SPDX-License-Identifier: MIT

apiVersion: v1
kind: Secret
metadata:
  name: idbridge-postgres
  namespace: open-idb
type: Opaque
stringData:
  POSTGRES_DB: idbridge
  POSTGRES_USER: idbridge
  POSTGRES_PASSWORD: idbridge-dev
  DATABASE_URL: postgres://idbridge:idbridge-dev@postgres.open-idb.svc.cluster.local:5432/idbridge?sslmode=disable
